<?php

class AdminMyModuleController extends ModuleAdminController
{
    public function l($sttring, $class = NULL, $addslashes = false, $htmlentities = true)
    {
        return $sttring;
    }

    public function __construct()
    {

        $this->table = "mymodule";
        $this->className = "MymoduleClass";
        $this->fields_list = array(
            'id_mymodule' => array('title' => 'ID'),
            'parameter' => array('title' => 'Message'),
        );

        $this->bootstrap = true;
        $this->addRowAction("view");
        $this->addRowAction("edit");
        $this->addRowAction("delete");

        // Set fields form for form view
        $this->context = Context::getContext();
        $this->context->controller = $this;
        $this->fields_form = array(
            'legend' => array(
                'title' => $this->l('Add / Edit Comment'),
                'image' => '../img/admin/contact.gif'
            ),
            'input' => array(
                array('type' => 'text', 'label' => $this->l('the parameter value'), 'name' =>
                    'parameter', 'size' => 30, 'required' => true),
                array('type' => 'text', 'label' => $this->l('the parameter value'), 'name' =>
                    'id_mymodule', 'size' => 30, 'required' => true)
            ),

            'submit' => array('title' => $this->l('Save'))
        );


        parent::__construct();
    }

    public function postProcess()
    {
        return parent::postProcess(); // TODO: Change the autogenerated stub
    }

    public function renderView()
    {
        $this->meta_title = $this->l('Comments on product');
        $this->toolbar_title[] = $this->meta_title;
        $tpl = $this->context->smarty->createTemplate(
            dirname(__FILE__) .
            '/../../views/templates/admin/view.tpl');
        return $tpl->fetch();
    }

}
