<?php

class MyModuleMessageModuleFrontController extends ModuleFrontController
{

    public function setMedia()
    {
        $this->registerStylesheet(
            "front-controller-mymodule",
            'modules/' . $this->module->name . '/views/templates/front/message.css',
            [
                'priority' => 999
            ]
        );
        return parent::setMedia(); // TODO: Change the autogenerated stub
    }

    public function initContent()
    {
        parent::initContent();
        $this->setTemplate("module:mymodule/views/templates/front/message.tpl");
    }

    public function postProcess()
    {
        if(Tools::getIsset('name')){
            echo "You submmitted" . Tools::getValue('name');

        }
        parent::postProcess(); // TODO: Change the autogenerated stub
    }
}